/**
 *  CONNECTORS_PHASE_3 — 50 strategic connectors for Indian DPDP MSP.
 *
 *  Phasing rationale (PM lens):
 *    3A  Indian-priority — where Indian SMB customers' PII actually lives
 *    3B  Global hot     — high-coverage international SaaS
 *    3C  Mid-priority   — analytics, mid-market, alternative DBs
 *    3D  Long tail      — payments alternatives, logistics, HR, marketplaces
 *
 *  Each definition is self-contained: connecting + discovery + DSR + event-log
 *  helpers all read these fields, so adding a connector is a single appended
 *  entry — no per-type switch statements anywhere downstream.
 */

import type {
  ConnectorDefinition,
  ConnectorDiscoveredField,
  ConnectorType,
} from "@prooflyt/contracts";

type Phase3Type = Exclude<
  ConnectorType,
  "HUBSPOT" | "RAZORPAY" | "FRESHDESK" | "ZOHO_CRM" | "SHOPIFY" | "POSTGRES" | "MONGODB" | "AWS_S3"
>;

/* ------------------------------------------------------------------ */
/*  Phase 3A — 10 Indian-priority                                      */
/* ------------------------------------------------------------------ */

const PHASE_3A: Record<Phase3Type, ConnectorDefinition> | any = {
  GOOGLE_WORKSPACE: {
    id: "GOOGLE_WORKSPACE", name: "Google Workspace", vendor: "Google LLC",
    category: "IDENTITY", authType: "OAUTH2", apiBaseUrl: "https://www.googleapis.com",
    oauthAuthorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
    oauthScopes: ["https://www.googleapis.com/auth/admin.directory.user.readonly", "https://www.googleapis.com/auth/admin.reports.audit.readonly", "https://www.googleapis.com/auth/drive.metadata.readonly", "https://www.googleapis.com/auth/gmail.readonly"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: true, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Workspace deletion via Admin SDK (users.delete) is permanent. For DSR exports, use Google Vault rather than per-user Takeout.",
      dataResidency: "US/EU/multi-region. India residency requires Workspace Enterprise + Data Regions add-on.",
      indianFootprint: "Most common email/identity stack for Indian SMBs. Often where Aadhaar/PAN spreadsheets surface.",
    },
    brand: { logoText: "GW", accentColor: "#4285f4" },
    serviceLabel: "Identity, mail, drive, calendar, audit logs",
    recordLabel: "users + shared documents", simulatedRecordCount: 12_847,
    discoveryWarnings: [
      "Workspace data resides outside India unless Data Regions is licensed. Disclose cross-border transfer.",
      "Drive shared-with-public links are a §16 surface — Prooflyt flags them in the audit log.",
    ],
    purposeTemplate: "Productivity & identity — {category} data captured for mail, file sharing, and identity management.",
    simulatedDsr: { exportCount: 23, eraseCount: 23 },
  },
  MOENGAGE: {
    id: "MOENGAGE", name: "MoEngage", vendor: "MoEngage Inc.",
    category: "MARKETING", authType: "API_KEY", apiBaseUrl: "https://api.moengage.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "MoEngage offers user-attribute deletion via Data Privacy API. Push-notification tokens are device-bound; ensure both attribute and segment removal.",
      dataResidency: "DC choice at workspace creation: India (in-mum), Europe, US. Confirm region before connecting.",
      indianFootprint: "Bangalore-origin. Massive Indian D2C, edtech, and fintech adoption.",
    },
    brand: { logoText: "ME", accentColor: "#1d6cf3" },
    serviceLabel: "Mobile + email engagement, push notifications, in-app messaging",
    recordLabel: "user profiles", simulatedRecordCount: 89_432,
    discoveryWarnings: ["MoEngage workspace region must match privacy notice residency claim. Push tokens require device-level erasure as well."],
    purposeTemplate: "Customer engagement — {category} data captured for marketing automation and lifecycle messaging.",
    simulatedDsr: { exportCount: 31, eraseCount: 31 },
  },
  WEBENGAGE: {
    id: "WEBENGAGE", name: "WebEngage", vendor: "WebEngage Software Pvt Ltd",
    category: "MARKETING", authType: "API_KEY", apiBaseUrl: "https://api.webengage.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "WebEngage Data Privacy Tools API supports user export and deletion. Anonymous events linked by deviceId need a separate purge call.",
      dataResidency: "India DC (Mumbai) is default for in.webengage.com accounts.",
      indianFootprint: "Mumbai-origin. Common in Indian D2C, edtech, fintech, OTT.",
    },
    brand: { logoText: "WE", accentColor: "#ff5722" },
    serviceLabel: "Multi-channel engagement, journeys, campaign analytics",
    recordLabel: "user profiles", simulatedRecordCount: 64_188,
    discoveryWarnings: ["Deletion requires both user-id and deviceId-linked event purges to be DPDP-complete."],
    purposeTemplate: "Marketing engagement — {category} data captured for journey orchestration and campaign analytics.",
    simulatedDsr: { exportCount: 28, eraseCount: 28 },
  },
  CLEVERTAP: {
    id: "CLEVERTAP", name: "CleverTap", vendor: "CleverTap (WizRocket)",
    category: "MARKETING", authType: "API_KEY", apiBaseUrl: "https://api.clevertap.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "CleverTap exposes a delete-profile endpoint. Identity-graph merges across devices need a profile-collapse step before deletion.",
      dataResidency: "DC choice at account creation: in1 (Mumbai), eu1, us1. Use in1 for DPDP residency.",
      indianFootprint: "Mumbai-origin. Major Indian mobile-first companies use CleverTap.",
    },
    brand: { logoText: "CT", accentColor: "#f64e60" },
    serviceLabel: "Mobile engagement, segmentation, journeys, analytics",
    recordLabel: "user profiles", simulatedRecordCount: 73_902,
    discoveryWarnings: ["Identity-graph merges can resurrect deleted profiles. Run delete + identity-collapse together."],
    purposeTemplate: "Mobile engagement — {category} data captured for segmentation and personalised messaging.",
    simulatedDsr: { exportCount: 26, eraseCount: 26 },
  },
  GUPSHUP: {
    id: "GUPSHUP", name: "Gupshup", vendor: "Gupshup Technology India Pvt Ltd",
    category: "COMMS", authType: "API_KEY", apiBaseUrl: "https://api.gupshup.io",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: true, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Message logs (DLR) are retained per regulatory norms. Phone-number-based PII deletion respects 6-month TRAI retention floor for SMS.",
      dataResidency: "India-only by default. Strong DPDP fit.",
      indianFootprint: "Bangalore-origin. India's largest conversational messaging platform; SMS, WhatsApp, RCS.",
    },
    brand: { logoText: "GS", accentColor: "#ff7d00" },
    serviceLabel: "SMS, WhatsApp Business, RCS, voice — conversational messaging",
    recordLabel: "messages + contacts", simulatedRecordCount: 312_478,
    discoveryWarnings: [
      "TRAI 6-month retention floor on SMS DLR may delay full erasure.",
      "WhatsApp opt-in records must be preserved as evidence per Meta policy.",
    ],
    purposeTemplate: "Conversational messaging — {category} data captured for OTPs, transactional alerts, and marketing.",
    simulatedDsr: { exportCount: 102, eraseCount: 102 },
  },
  EXOTEL: {
    id: "EXOTEL", name: "Exotel", vendor: "Exotel Techcom Pvt Ltd",
    category: "COMMS", authType: "API_KEY", apiBaseUrl: "https://api.exotel.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: true, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Call recordings are sensitive PII. TRAI mandates retention for some categories — confirm before erasure.",
      dataResidency: "India-only DC (DOT licence). Strong DPDP fit.",
      indianFootprint: "Bangalore-origin. Cloud telephony backbone for Indian SMBs.",
    },
    brand: { logoText: "EX", accentColor: "#1d2630" },
    serviceLabel: "Cloud telephony — call routing, IVR, recordings, virtual numbers",
    recordLabel: "calls + recordings", simulatedRecordCount: 28_643,
    discoveryWarnings: [
      "Call recordings are sensitive PII; ensure access controls before bulk export.",
      "TRAI Class A licence retention rules may delay erasure.",
    ],
    purposeTemplate: "Cloud telephony — {category} data captured for IVR, virtual numbers, and call recordings.",
    simulatedDsr: { exportCount: 18, eraseCount: 18 },
  },
  WHATSAPP_BUSINESS: {
    id: "WHATSAPP_BUSINESS", name: "WhatsApp Business API", vendor: "Meta Platforms, Inc.",
    category: "COMMS", authType: "OAUTH2", apiBaseUrl: "https://graph.facebook.com",
    oauthAuthorizeUrl: "https://www.facebook.com/v18.0/dialog/oauth",
    oauthTokenUrl: "https://graph.facebook.com/v18.0/oauth/access_token",
    oauthScopes: ["whatsapp_business_management", "whatsapp_business_messaging"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: true, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Meta retains messaging metadata; opt-in records are mandatory evidence and cannot be deleted before regulatory window expires.",
      dataResidency: "Multi-region (US/EU primary). Disclose cross-border transfer.",
      indianFootprint: "India's #1 customer messaging channel. Almost every Indian D2C uses WhatsApp Business.",
    },
    brand: { logoText: "WA", accentColor: "#25d366" },
    serviceLabel: "Customer messaging — templates, sessions, opt-in records",
    recordLabel: "conversations + contacts", simulatedRecordCount: 145_290,
    discoveryWarnings: [
      "Opt-in records are mandatory evidence per Meta policy and cannot be deleted before retention window.",
      "Cross-border transfer disclosure is required.",
    ],
    purposeTemplate: "Customer messaging — {category} data captured for transactional + utility WhatsApp messaging.",
    simulatedDsr: { exportCount: 67, eraseCount: 67 },
  },
  CASHFREE: {
    id: "CASHFREE", name: "Cashfree", vendor: "Cashfree Payments India Pvt Ltd",
    category: "PAYMENTS", authType: "API_KEY", apiBaseUrl: "https://api.cashfree.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: false, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "RBI 5–10 year retention. Same DPDP §17(2)(a) denial path as Razorpay.",
      dataResidency: "India only (RBI mandate).",
      indianFootprint: "Bangalore-origin. Top-3 Indian payment gateway.",
    },
    brand: { logoText: "CF", accentColor: "#3b59f5" },
    serviceLabel: "Payment gateway — UPI, cards, net-banking, payouts",
    recordLabel: "customers + transactions", simulatedRecordCount: 9_847,
    discoveryWarnings: ["Cashfree records are subject to RBI 5–10 year retention. Erasure denied under DPDP §17(2)(a)."],
    purposeTemplate: "Payment processing — {category} data captured for transaction fulfilment and reconciliation.",
    simulatedDsr: { exportCount: 33, eraseCount: 0 },
  },
  PAYU: {
    id: "PAYU", name: "PayU", vendor: "PayU Payments Pvt Ltd",
    category: "PAYMENTS", authType: "API_KEY", apiBaseUrl: "https://info.payu.in",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: false, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "RBI 5–10 year retention. DPDP §17(2)(a) denial.",
      dataResidency: "India only.",
      indianFootprint: "One of India's earliest payment gateways. Strong enterprise + SMB footprint.",
    },
    brand: { logoText: "PU", accentColor: "#19a04b" },
    serviceLabel: "Payment gateway — cards, UPI, EMI, BNPL",
    recordLabel: "customers + transactions", simulatedRecordCount: 7_542,
    discoveryWarnings: ["PayU records are subject to RBI 5–10 year retention. Erasure denied under DPDP §17(2)(a)."],
    purposeTemplate: "Payment processing — {category} data captured for transaction fulfilment and reconciliation.",
    simulatedDsr: { exportCount: 29, eraseCount: 0 },
  },
  SHIPROCKET: {
    id: "SHIPROCKET", name: "Shiprocket", vendor: "BigFoot Retail Solutions Pvt Ltd",
    category: "LOGISTICS", authType: "API_KEY", apiBaseUrl: "https://apiv2.shiprocket.in",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Order records are retained for tax/audit (8 years GST Act). Buyer PII deletion is constrained by audit-trail requirements.",
      dataResidency: "India only.",
      indianFootprint: "Delhi-origin. India's #1 D2C shipping aggregator. Nearly every Indian D2C uses it.",
    },
    brand: { logoText: "SR", accentColor: "#1a73e8" },
    serviceLabel: "Shipping aggregation — courier rates, AWB, tracking, RTO management",
    recordLabel: "shipments + buyers", simulatedRecordCount: 18_624,
    discoveryWarnings: [
      "8-year GST retention floor on shipment records.",
      "Buyer name + address + phone are direct identifiers — flag for sensitive PII handling.",
    ],
    purposeTemplate: "Shipping & fulfilment — {category} data captured for courier coordination, tracking, and reverse logistics.",
    simulatedDsr: { exportCount: 14, eraseCount: 14 },
  },

  /* ── Phase 3B — 10 global hot ──────────────────────────────────── */
  MICROSOFT_365: {
    id: "MICROSOFT_365", name: "Microsoft 365", vendor: "Microsoft Corporation",
    category: "IDENTITY", authType: "OAUTH2", apiBaseUrl: "https://graph.microsoft.com",
    oauthAuthorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    oauthTokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    oauthScopes: ["User.Read.All", "AuditLog.Read.All", "Files.Read.All", "Mail.Read"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: true, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Microsoft 365 retains audit logs per tenant policy. Compliance Manager handles DSR exports natively.",
      dataResidency: "India DC available (Microsoft India regions). Confirm tenant region.",
      indianFootprint: "Enterprise-default; large Indian SMB / mid-market footprint.",
    },
    brand: { logoText: "M3", accentColor: "#0078d4" },
    serviceLabel: "Identity, Outlook, Teams, SharePoint, OneDrive",
    recordLabel: "users + mailboxes + files", simulatedRecordCount: 9_204,
    discoveryWarnings: ["Confirm tenant Data Residency setting matches the privacy notice claim."],
    purposeTemplate: "Productivity & identity — {category} data captured for mail, collaboration, and identity.",
    simulatedDsr: { exportCount: 18, eraseCount: 18 },
  },
  MAILCHIMP: {
    id: "MAILCHIMP", name: "Mailchimp", vendor: "Intuit Inc.",
    category: "MARKETING", authType: "OAUTH2", apiBaseUrl: "https://us1.api.mailchimp.com",
    oauthAuthorizeUrl: "https://login.mailchimp.com/oauth2/authorize",
    oauthTokenUrl: "https://login.mailchimp.com/oauth2/token",
    oauthScopes: [],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Mailchimp permanently deletes contacts via the Members API delete-permanent endpoint. Archived contacts remain unless purged.",
      dataResidency: "US (Mailchimp data centres). Disclose cross-border transfer.",
      indianFootprint: "Most common SMB email marketing tool worldwide.",
    },
    brand: { logoText: "MC", accentColor: "#ffe01b" },
    serviceLabel: "Email marketing — lists, campaigns, automations",
    recordLabel: "subscribers", simulatedRecordCount: 22_415,
    discoveryWarnings: ["Mailchimp data resides outside India. Disclose cross-border transfer in the privacy notice."],
    purposeTemplate: "Email marketing — {category} data captured for newsletter, campaign, and automation delivery.",
    simulatedDsr: { exportCount: 16, eraseCount: 16 },
  },
  SENDGRID: {
    id: "SENDGRID", name: "SendGrid", vendor: "Twilio Inc.",
    category: "MARKETING", authType: "API_KEY", apiBaseUrl: "https://api.sendgrid.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Email logs (events) retained for analytics. Suppression lists must persist after deletion to honour bounce/unsubscribe state.",
      dataResidency: "US (Twilio data centres). EU residency available on request.",
      indianFootprint: "Default transactional email provider for Indian SaaS.",
    },
    brand: { logoText: "SG", accentColor: "#1a82e2" },
    serviceLabel: "Transactional email + analytics",
    recordLabel: "emails + recipients", simulatedRecordCount: 184_293,
    discoveryWarnings: ["Suppression lists must persist after deletion to honour unsubscribe state under DPDP §6 consent withdrawal."],
    purposeTemplate: "Transactional email — {category} data captured for delivery, bounce handling, and analytics.",
    simulatedDsr: { exportCount: 41, eraseCount: 41 },
  },
  TWILIO: {
    id: "TWILIO", name: "Twilio", vendor: "Twilio Inc.",
    category: "COMMS", authType: "API_KEY", apiBaseUrl: "https://api.twilio.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Message + call logs retained per Twilio policy. India-bound SMS may carry DLT TRAI retention.",
      dataResidency: "US/EU/AU regional storage. India data may transit via US.",
      indianFootprint: "Default international SMS/voice for Indian SaaS.",
    },
    brand: { logoText: "TW", accentColor: "#f22f46" },
    serviceLabel: "Programmable SMS, voice, video, email",
    recordLabel: "messages + calls", simulatedRecordCount: 76_402,
    discoveryWarnings: [
      "DLT TRAI 6-month SMS retention floor for India-bound messages.",
      "Cross-border transfer disclosure required.",
    ],
    purposeTemplate: "Programmable communications — {category} data captured for OTP, alerts, and voice operations.",
    simulatedDsr: { exportCount: 38, eraseCount: 38 },
  },
  STRIPE: {
    id: "STRIPE", name: "Stripe", vendor: "Stripe, Inc.",
    category: "PAYMENTS", authType: "API_KEY", apiBaseUrl: "https://api.stripe.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: false, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Stripe retains payment records for legal/financial compliance. PII redaction available; full deletion is not.",
      dataResidency: "US/EU/Asia (multi-region). Stripe India is a separate entity under RBI.",
      indianFootprint: "International payments for Indian SaaS; Stripe India is RBI-licensed.",
    },
    brand: { logoText: "ST", accentColor: "#635bff" },
    serviceLabel: "Card processing, subscriptions, invoices, payouts",
    recordLabel: "customers + payments", simulatedRecordCount: 6_207,
    discoveryWarnings: [
      "Stripe retention obligations conflict with DSR erasure — Prooflyt issues a denial letter where applicable.",
      "Stripe India (rzn entity) is RBI-bound; cross-border records may be processed via Stripe US.",
    ],
    purposeTemplate: "Card processing — {category} data captured for subscriptions, invoices, and payouts.",
    simulatedDsr: { exportCount: 21, eraseCount: 0 },
  },
  SALESFORCE: {
    id: "SALESFORCE", name: "Salesforce", vendor: "Salesforce, Inc.",
    category: "CRM", authType: "OAUTH2", apiBaseUrl: "https://login.salesforce.com",
    oauthAuthorizeUrl: "https://login.salesforce.com/services/oauth2/authorize",
    oauthTokenUrl: "https://login.salesforce.com/services/oauth2/token",
    oauthScopes: ["api", "refresh_token"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Salesforce data masking + record deletion are first-class. Custom objects + flows may need per-tenant audit.",
      dataResidency: "Hyperforce India (Mumbai) regional pinning available for Enterprise Edition+.",
      indianFootprint: "Enterprise CRM standard; large Indian mid-market and enterprise install base.",
    },
    brand: { logoText: "SF", accentColor: "#00a1e0" },
    serviceLabel: "Sales, service, marketing cloud — lead/contact/opportunity",
    recordLabel: "contacts + leads + accounts", simulatedRecordCount: 28_104,
    discoveryWarnings: ["Confirm Hyperforce India pinning if residency is claimed."],
    purposeTemplate: "Enterprise CRM — {category} data captured for sales, service, and marketing automation.",
    simulatedDsr: { exportCount: 24, eraseCount: 24 },
  },
  SLACK: {
    id: "SLACK", name: "Slack", vendor: "Slack Technologies, LLC (Salesforce)",
    category: "COLLABORATION", authType: "OAUTH2", apiBaseUrl: "https://slack.com/api",
    oauthAuthorizeUrl: "https://slack.com/oauth/v2/authorize",
    oauthTokenUrl: "https://slack.com/api/oauth.v2.access",
    oauthScopes: ["users:read", "files:read", "channels:history", "groups:history"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Slack message retention is workspace-policy. DM exports require Plus plan + Compliance Export.",
      dataResidency: "US/EU/AP regions. India data typically routed via US.",
      indianFootprint: "Internal-comms default for Indian SaaS. Holds employee + cross-tenant PII.",
    },
    brand: { logoText: "SL", accentColor: "#4a154b" },
    serviceLabel: "Internal messaging — channels, DMs, files, workflows",
    recordLabel: "users + messages", simulatedRecordCount: 8_193,
    discoveryWarnings: ["DM exports require Plus plan + Compliance Export. Free-tier history is capped at 90 days but keeps PII metadata."],
    purposeTemplate: "Internal collaboration — {category} data captured for team messaging and file sharing.",
    simulatedDsr: { exportCount: 19, eraseCount: 19 },
  },
  GOOGLE_DRIVE: {
    id: "GOOGLE_DRIVE", name: "Google Drive", vendor: "Google LLC",
    category: "STORAGE_DOC", authType: "OAUTH2", apiBaseUrl: "https://www.googleapis.com",
    oauthAuthorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
    oauthScopes: ["https://www.googleapis.com/auth/drive.metadata.readonly"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Drive trash is 30-day default. DPDP-grade erasure requires permanent delete + revision purge.",
      dataResidency: "US/EU/multi-region. India residency requires Workspace Enterprise + Data Regions.",
      indianFootprint: "Default file storage for Indian SMBs running on Google Workspace.",
    },
    brand: { logoText: "GD", accentColor: "#1ea362" },
    serviceLabel: "File storage + sharing — docs, sheets, slides, uploads",
    recordLabel: "files + folders", simulatedRecordCount: 34_521,
    discoveryWarnings: [
      "Spreadsheets are the highest-density PII surface (customer lists, exports). Flag *.xlsx + *.csv files.",
      "Public-link sharing is a §16 surface — Prooflyt audits and reports it.",
    ],
    purposeTemplate: "File storage — {category} data captured as uploaded documents, sheets, and exports.",
    simulatedDsr: { exportCount: 12, eraseCount: 12 },
  },
  NOTION: {
    id: "NOTION", name: "Notion", vendor: "Notion Labs, Inc.",
    category: "COLLABORATION", authType: "OAUTH2", apiBaseUrl: "https://api.notion.com",
    oauthAuthorizeUrl: "https://api.notion.com/v1/oauth/authorize",
    oauthTokenUrl: "https://api.notion.com/v1/oauth/token",
    oauthScopes: [],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: false, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Notion page deletion archives; permanent purge is workspace-policy. Database pages with PII need separate audit.",
      dataResidency: "US (AWS us-east). Disclose cross-border transfer.",
      indianFootprint: "Internal docs / wiki default for Indian startups.",
    },
    brand: { logoText: "NT", accentColor: "#000000" },
    serviceLabel: "Internal docs + databases + wiki",
    recordLabel: "pages + databases", simulatedRecordCount: 4_381,
    discoveryWarnings: ["Customer-data spreadsheets in Notion databases are common; flag for explicit retention policy."],
    purposeTemplate: "Internal knowledge & docs — {category} data captured in pages, databases, and shared notes.",
    simulatedDsr: { exportCount: 9, eraseCount: 9 },
  },
  ZENDESK: {
    id: "ZENDESK", name: "Zendesk", vendor: "Zendesk, Inc.",
    category: "HELPDESK", authType: "API_KEY", apiBaseUrl: "",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: true, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Zendesk Sunshine end-user delete is permanent. Ticket attachments require explicit purge.",
      dataResidency: "US/EU/AU/JP regional pinning. India data typically via US.",
      indianFootprint: "Mid-market helpdesk in Indian SaaS. Alternative to Freshdesk.",
    },
    brand: { logoText: "ZD", accentColor: "#03363d" },
    serviceLabel: "Helpdesk tickets, end-user PII, support automation",
    recordLabel: "tickets + end-users", simulatedRecordCount: 11_847,
    discoveryWarnings: ["Ticket attachments require explicit purge after end-user delete."],
    purposeTemplate: "Customer support — {category} data captured for ticket resolution and customer history.",
    simulatedDsr: { exportCount: 17, eraseCount: 17 },
  },

  /* ── Phase 3C — 15 mid-priority ─────────────────────────────────── */
  KLAVIYO: {
    id: "KLAVIYO", name: "Klaviyo", vendor: "Klaviyo, Inc.",
    category: "MARKETING", authType: "API_KEY", apiBaseUrl: "https://a.klaviyo.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Klaviyo profile deletion is GDPR-grade and permanent. Suppression list persists after deletion.",
      dataResidency: "US (default). EU available.",
      indianFootprint: "Default marketing for Shopify-running Indian D2C.",
    },
    brand: { logoText: "KL", accentColor: "#0a0d0e" },
    serviceLabel: "E-commerce email + SMS marketing, segmentation",
    recordLabel: "profiles + segments", simulatedRecordCount: 18_204,
    discoveryWarnings: ["Suppression list persists after deletion to honour DPDP §6 consent withdrawal."],
    purposeTemplate: "E-commerce marketing — {category} data captured for email, SMS, segmentation.",
    simulatedDsr: { exportCount: 14, eraseCount: 14 },
  },
  AUTH0: {
    id: "AUTH0", name: "Auth0", vendor: "Okta, Inc.",
    category: "IDENTITY", authType: "OAUTH2", apiBaseUrl: "",
    oauthAuthorizeUrl: "", oauthTokenUrl: "", oauthScopes: ["read:users", "delete:users"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Auth0 user delete is permanent. Identity-provider linkages require unlink before delete.",
      dataResidency: "US/EU/AU regions. No India DC currently.",
      indianFootprint: "Common in Indian SaaS auth stack. Mid-market and developer-default.",
    },
    brand: { logoText: "A0", accentColor: "#eb5424" },
    serviceLabel: "Authentication & authorisation as a service",
    recordLabel: "users + sessions", simulatedRecordCount: 29_481,
    discoveryWarnings: ["IdP linkages must be unlinked before user deletion to avoid orphaned identities."],
    purposeTemplate: "Identity & access — {category} data captured for authentication and session management.",
    simulatedDsr: { exportCount: 22, eraseCount: 22 },
  },
  OKTA: {
    id: "OKTA", name: "Okta", vendor: "Okta, Inc.",
    category: "IDENTITY", authType: "API_KEY", apiBaseUrl: "",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Okta user lifecycle: deactivate → suspend → delete. DSR exports include factor enrolments.",
      dataResidency: "US/EU/CA/AU. India residency not available.",
      indianFootprint: "Enterprise IdP for Indian mid-market and SaaS B2B.",
    },
    brand: { logoText: "OK", accentColor: "#007dc1" },
    serviceLabel: "Workforce + customer identity, SSO, lifecycle",
    recordLabel: "users + factor enrolments", simulatedRecordCount: 12_408,
    discoveryWarnings: ["Lifecycle deletion is multi-step (deactivate → suspend → delete). Each transition is recorded as evidence."],
    purposeTemplate: "Identity & access — {category} data captured for SSO, MFA, and lifecycle management.",
    simulatedDsr: { exportCount: 19, eraseCount: 19 },
  },
  FIREBASE_AUTH: {
    id: "FIREBASE_AUTH", name: "Firebase Authentication", vendor: "Google LLC",
    category: "IDENTITY", authType: "API_KEY", apiBaseUrl: "https://identitytoolkit.googleapis.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: false, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Firebase deletes user accounts permanently. Linked Firestore/RTDB data needs separate purge.",
      dataResidency: "Multi-region; India residency on Firestore requires region pinning.",
      indianFootprint: "Default auth for Indian mobile-first startups.",
    },
    brand: { logoText: "FA", accentColor: "#ffca28" },
    serviceLabel: "Mobile + web authentication — email, phone, social, anonymous",
    recordLabel: "users + sessions", simulatedRecordCount: 41_290,
    discoveryWarnings: ["Linked Firestore/RTDB documents must be purged separately after Firebase Auth user delete."],
    purposeTemplate: "Mobile authentication — {category} data captured for email, phone, and social login.",
    simulatedDsr: { exportCount: 26, eraseCount: 26 },
  },
  GOOGLE_ANALYTICS_4: {
    id: "GOOGLE_ANALYTICS_4", name: "Google Analytics 4", vendor: "Google LLC",
    category: "ANALYTICS", authType: "OAUTH2", apiBaseUrl: "https://analyticsadmin.googleapis.com",
    oauthAuthorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
    oauthScopes: ["https://www.googleapis.com/auth/analytics.edit"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: false, grievanceIngest: false, webhooks: false, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "User-deletion API removes attributable events. Aggregate analytics are retained.",
      dataResidency: "US (multi-region). India residency not available.",
      indianFootprint: "Universal — every Indian site has GA4 unless deliberately removed.",
    },
    brand: { logoText: "GA", accentColor: "#f9ab00" },
    serviceLabel: "Web + app analytics — events, audiences, attribution",
    recordLabel: "user_pseudo_id events", simulatedRecordCount: 478_204,
    discoveryWarnings: ["GA4 cookie banners must align with DPDP §6 consent. Prooflyt audits the consent banner config."],
    purposeTemplate: "Analytics — {category} data captured for product analytics, audiences, and attribution.",
    simulatedDsr: { exportCount: 0, eraseCount: 89 },
  },
  MIXPANEL: {
    id: "MIXPANEL", name: "Mixpanel", vendor: "Mixpanel, Inc.",
    category: "ANALYTICS", authType: "API_KEY", apiBaseUrl: "https://mixpanel.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: false, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Mixpanel user-delete API removes all events for a distinct_id. Aggregates retained.",
      dataResidency: "US/EU. No India DC.",
      indianFootprint: "Common in Indian product-led SaaS.",
    },
    brand: { logoText: "MP", accentColor: "#7856ff" },
    serviceLabel: "Product analytics — events, funnels, retention",
    recordLabel: "distinct_id events", simulatedRecordCount: 264_850,
    discoveryWarnings: ["Cross-project identity-merge can resurrect deleted profiles. Run delete + identity-collapse together."],
    purposeTemplate: "Product analytics — {category} data captured for event-driven product insights.",
    simulatedDsr: { exportCount: 47, eraseCount: 47 },
  },
  AMPLITUDE: {
    id: "AMPLITUDE", name: "Amplitude", vendor: "Amplitude, Inc.",
    category: "ANALYTICS", authType: "API_KEY", apiBaseUrl: "https://amplitude.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: false, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Amplitude DSAR API supports user export and full delete.",
      dataResidency: "US/EU. India residency unavailable.",
      indianFootprint: "Used in Indian SaaS and consumer mobile.",
    },
    brand: { logoText: "AM", accentColor: "#1976ed" },
    serviceLabel: "Behavioural analytics — events, cohorts, paths",
    recordLabel: "user events", simulatedRecordCount: 192_481,
    discoveryWarnings: ["Cross-project identity merges may need explicit collapse before delete."],
    purposeTemplate: "Behavioural analytics — {category} data captured for product engagement and cohort analysis.",
    simulatedDsr: { exportCount: 39, eraseCount: 39 },
  },
  SEGMENT: {
    id: "SEGMENT", name: "Segment", vendor: "Twilio Inc.",
    category: "ANALYTICS", authType: "API_KEY", apiBaseUrl: "https://platform.segmentapis.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Segment Privacy Portal supports user-id-based suppression that propagates to connected destinations. Critical for fan-out DSR.",
      dataResidency: "US/EU. India residency unavailable.",
      indianFootprint: "CDP backbone for mid-market Indian SaaS.",
    },
    brand: { logoText: "SG", accentColor: "#52bd95" },
    serviceLabel: "Customer Data Platform — track, identify, fan-out to destinations",
    recordLabel: "users + events", simulatedRecordCount: 521_380,
    discoveryWarnings: ["Segment fan-outs to other destinations — deletion at Segment must propagate downstream. Audit destination receipts."],
    purposeTemplate: "Customer data platform — {category} data captured for routing and identity resolution.",
    simulatedDsr: { exportCount: 84, eraseCount: 84 },
  },
  POSTHOG: {
    id: "POSTHOG", name: "PostHog", vendor: "PostHog, Inc.",
    category: "ANALYTICS", authType: "API_KEY", apiBaseUrl: "https://app.posthog.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "PostHog person-delete is permanent. Self-hosted option allows India residency.",
      dataResidency: "US Cloud / EU Cloud / Self-hosted. Self-hosted on Indian infra is DPDP-friendly.",
      indianFootprint: "Growing among Indian privacy-conscious startups.",
    },
    brand: { logoText: "PH", accentColor: "#1d4aff" },
    serviceLabel: "Product analytics — events, session recordings, feature flags",
    recordLabel: "person events", simulatedRecordCount: 73_201,
    discoveryWarnings: [
      "Session recordings (rrweb) capture form-input PII unless masked. Enable input-masking before connecting.",
      "Self-hosted is DPDP-friendly; cloud option needs cross-border disclosure.",
    ],
    purposeTemplate: "Product analytics — {category} data captured for events, replays, and feature experimentation.",
    simulatedDsr: { exportCount: 28, eraseCount: 28 },
  },
  PIPEDRIVE: {
    id: "PIPEDRIVE", name: "Pipedrive", vendor: "Pipedrive Inc.",
    category: "CRM", authType: "OAUTH2", apiBaseUrl: "https://api.pipedrive.com",
    oauthAuthorizeUrl: "https://oauth.pipedrive.com/oauth/authorize",
    oauthTokenUrl: "https://oauth.pipedrive.com/oauth/token",
    oauthScopes: ["base"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Pipedrive permanent-delete clears person + deal + activity history.",
      dataResidency: "US/EU. No India DC.",
      indianFootprint: "SMB-friendly CRM, growing in Indian B2B SaaS.",
    },
    brand: { logoText: "PD", accentColor: "#017737" },
    serviceLabel: "Sales pipeline CRM — persons, deals, activities",
    recordLabel: "persons + deals", simulatedRecordCount: 7_812,
    discoveryWarnings: ["Permanent delete is irreversible — confirm 30-day grace period elapsed first."],
    purposeTemplate: "Sales pipeline — {category} data captured for lead nurture, deal tracking, and forecast.",
    simulatedDsr: { exportCount: 11, eraseCount: 11 },
  },
  LEADSQUARED: {
    id: "LEADSQUARED", name: "LeadSquared", vendor: "MarketXpander Services Pvt Ltd",
    category: "CRM", authType: "API_KEY", apiBaseUrl: "https://api.leadsquared.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "LeadSquared GDPR-grade lead-delete is supported. Edtech use-cases often have audit-retention obligations.",
      dataResidency: "India DC available (preferred for DPDP).",
      indianFootprint: "Bangalore-origin. Edtech, BFSI, real-estate vertical CRM dominance.",
    },
    brand: { logoText: "LS", accentColor: "#1c8df3" },
    serviceLabel: "Sales execution CRM — leads, automation, dialer",
    recordLabel: "leads + activities", simulatedRecordCount: 16_421,
    discoveryWarnings: ["Confirm DC (in-mum) is selected at workspace creation for DPDP residency."],
    purposeTemplate: "Sales execution — {category} data captured for lead nurture, dialer, and journey automation.",
    simulatedDsr: { exportCount: 18, eraseCount: 18 },
  },
  WOOCOMMERCE: {
    id: "WOOCOMMERCE", name: "WooCommerce", vendor: "Automattic, Inc.",
    category: "ECOMMERCE", authType: "API_KEY", apiBaseUrl: "",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "WooCommerce on self-hosted WP — deletion depends on host. GDPR plug-ins exist.",
      dataResidency: "Depends on host. Often Indian shared-hosting.",
      indianFootprint: "Common in Indian D2C running on WordPress.",
    },
    brand: { logoText: "WC", accentColor: "#7f54b3" },
    serviceLabel: "WordPress-native e-commerce — products, orders, customers",
    recordLabel: "customers + orders", simulatedRecordCount: 9_204,
    discoveryWarnings: ["Self-hosted — confirm host residency and backup retention before claiming DPDP compliance."],
    purposeTemplate: "E-commerce — {category} data captured for orders, customer accounts, and shipping.",
    simulatedDsr: { exportCount: 13, eraseCount: 13 },
  },
  MAGENTO: {
    id: "MAGENTO", name: "Magento (Adobe Commerce)", vendor: "Adobe Inc.",
    category: "ECOMMERCE", authType: "OAUTH2", apiBaseUrl: "",
    oauthAuthorizeUrl: "", oauthTokenUrl: "", oauthScopes: [],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Adobe Commerce GDPR module supports DSR exports + delete with order-history retention.",
      dataResidency: "Multi-region. India residency requires Adobe Experience Cloud setup.",
      indianFootprint: "Indian mid-market B2C and B2B e-commerce.",
    },
    brand: { logoText: "MG", accentColor: "#ee672f" },
    serviceLabel: "Mid-market e-commerce — catalog, customer, order, B2B",
    recordLabel: "customers + orders", simulatedRecordCount: 14_802,
    discoveryWarnings: ["B2B accounts may have multi-buyer hierarchies needing per-contact handling."],
    purposeTemplate: "E-commerce — {category} data captured for catalog, orders, and B2B account management.",
    simulatedDsr: { exportCount: 22, eraseCount: 22 },
  },
  INTERCOM: {
    id: "INTERCOM", name: "Intercom", vendor: "Intercom, Inc.",
    category: "HELPDESK", authType: "OAUTH2", apiBaseUrl: "https://api.intercom.io",
    oauthAuthorizeUrl: "https://app.intercom.com/oauth", oauthTokenUrl: "https://api.intercom.io/auth/eagle/token",
    oauthScopes: [],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: true, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Intercom permanent-delete user is GDPR-grade. Conversations + tags + attributes purged.",
      dataResidency: "US/EU/AU. No India DC.",
      indianFootprint: "Indian SaaS support default. Common B2B/SaaS install.",
    },
    brand: { logoText: "IC", accentColor: "#0057ff" },
    serviceLabel: "Customer messaging + support — inbox, conversations, attributes",
    recordLabel: "users + conversations", simulatedRecordCount: 16_209,
    discoveryWarnings: ["Conversation attachments require explicit purge after user delete."],
    purposeTemplate: "Customer messaging & support — {category} data captured for live chat, ticketing, and CSM.",
    simulatedDsr: { exportCount: 21, eraseCount: 21 },
  },
  JIRA: {
    id: "JIRA", name: "Jira", vendor: "Atlassian Pty Ltd",
    category: "COLLABORATION", authType: "OAUTH2", apiBaseUrl: "https://api.atlassian.com",
    oauthAuthorizeUrl: "https://auth.atlassian.com/authorize",
    oauthTokenUrl: "https://auth.atlassian.com/oauth/token",
    oauthScopes: ["read:jira-user", "read:jira-work"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: {
      legalBasisFloor: "Atlassian Cloud user delete is GDPR-grade. Bug-report PII (steps-to-reproduce) often contains user data.",
      dataResidency: "Atlassian Cloud Premium offers regional pinning. India not yet available.",
      indianFootprint: "Engineering team default for Indian SaaS.",
    },
    brand: { logoText: "JR", accentColor: "#0052cc" },
    serviceLabel: "Issue tracker — projects, issues, comments, attachments",
    recordLabel: "issues + reporters", simulatedRecordCount: 8_421,
    discoveryWarnings: ["Bug reports often paste in customer PII (steps to reproduce). Audit user-supplied content."],
    purposeTemplate: "Issue tracking — {category} data captured for software defect and request management.",
    simulatedDsr: { exportCount: 14, eraseCount: 14 },
  },

  /* ── Phase 3D — 15 final ────────────────────────────────────────── */
  PAYTM_BUSINESS: {
    id: "PAYTM_BUSINESS", name: "Paytm Business", vendor: "One97 Communications Ltd",
    category: "PAYMENTS", authType: "API_KEY", apiBaseUrl: "https://securegw.paytm.in",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: false, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "RBI 5–10 year retention; same DPDP §17(2)(a) denial path.", dataResidency: "India only.", indianFootprint: "Strong Indian SMB + offline merchant footprint." },
    brand: { logoText: "PT", accentColor: "#012b72" },
    serviceLabel: "Payment gateway — UPI, wallet, EDC", recordLabel: "merchants + customers", simulatedRecordCount: 8_204,
    discoveryWarnings: ["Subject to RBI retention. Erasure denied under DPDP §17(2)(a)."],
    purposeTemplate: "Payment processing — {category} data captured for transaction fulfilment.",
    simulatedDsr: { exportCount: 32, eraseCount: 0 },
  },
  PHONEPE_BUSINESS: {
    id: "PHONEPE_BUSINESS", name: "PhonePe Business", vendor: "PhonePe Pvt Ltd",
    category: "PAYMENTS", authType: "API_KEY", apiBaseUrl: "https://api.phonepe.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: false, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "RBI 5–10 year retention; DPDP §17(2)(a) denial.", dataResidency: "India only (RBI mandate).", indianFootprint: "India's #1 UPI platform; large merchant footprint." },
    brand: { logoText: "PP", accentColor: "#5f259f" },
    serviceLabel: "UPI + wallet payments, merchant settlements", recordLabel: "merchants + transactions", simulatedRecordCount: 10_402,
    discoveryWarnings: ["Subject to RBI retention. Erasure denied under DPDP §17(2)(a)."],
    purposeTemplate: "UPI processing — {category} data captured for transaction fulfilment.",
    simulatedDsr: { exportCount: 28, eraseCount: 0 },
  },
  DELHIVERY: {
    id: "DELHIVERY", name: "Delhivery", vendor: "Delhivery Ltd",
    category: "LOGISTICS", authType: "API_KEY", apiBaseUrl: "https://track.delhivery.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "GST Act 8-year retention floor on shipment + invoice records.", dataResidency: "India only.", indianFootprint: "Listed Indian unicorn; major D2C / e-commerce courier." },
    brand: { logoText: "DV", accentColor: "#d32f2f" },
    serviceLabel: "Courier + supply chain — last-mile, RTO, COD", recordLabel: "shipments + buyers", simulatedRecordCount: 21_403,
    discoveryWarnings: ["8-year GST retention on shipment records constrains erasure."],
    purposeTemplate: "Shipping & logistics — {category} data captured for last-mile, RTO, and COD reconciliation.",
    simulatedDsr: { exportCount: 16, eraseCount: 16 },
  },
  BLUEDART: {
    id: "BLUEDART", name: "BlueDart", vendor: "Blue Dart Express Ltd (DHL)",
    category: "LOGISTICS", authType: "API_KEY", apiBaseUrl: "https://api.bluedart.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: false, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "GST + audit retention; international parcels carry customs records.", dataResidency: "India ops, DHL group multi-region.", indianFootprint: "Premium courier; common in Indian B2B and high-value D2C." },
    brand: { logoText: "BD", accentColor: "#f7931d" },
    serviceLabel: "Courier — domestic + international + cross-border customs", recordLabel: "shipments + consignees", simulatedRecordCount: 7_482,
    discoveryWarnings: ["International shipments include consignee details required for customs — retention is statutory."],
    purposeTemplate: "Premium courier — {category} data captured for shipment, customs, and tracking.",
    simulatedDsr: { exportCount: 9, eraseCount: 9 },
  },
  KEKA: {
    id: "KEKA", name: "Keka", vendor: "Keka Technologies Pvt Ltd",
    category: "HR", authType: "API_KEY", apiBaseUrl: "https://api.keka.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: true, webhooks: true, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "Employment records carry statutory retention (5+ years per Indian labour law).", dataResidency: "India only.", indianFootprint: "Hyderabad-origin. Common Indian SMB HRMS." },
    brand: { logoText: "KK", accentColor: "#0086c9" },
    serviceLabel: "HRMS — payroll, attendance, performance, exit", recordLabel: "employees + payroll", simulatedRecordCount: 1_204,
    discoveryWarnings: [
      "Aadhaar/PAN holdings require Section 7 sensitive-PII handling.",
      "Statutory employment retention (≥5 years) constrains erasure post-exit.",
    ],
    purposeTemplate: "HR & payroll — {category} data captured for employment lifecycle.",
    simulatedDsr: { exportCount: 7, eraseCount: 7 },
  },
  DARWINBOX: {
    id: "DARWINBOX", name: "Darwinbox", vendor: "Darwinbox Digital Solutions Pvt Ltd",
    category: "HR", authType: "API_KEY", apiBaseUrl: "https://api.darwinbox.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: true, webhooks: true, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "Statutory employment retention; exit/separation flows must preserve audit trail.", dataResidency: "India DC available (default for in.darwinbox.com).", indianFootprint: "Hyderabad-origin. Enterprise HRMS for Indian + APAC mid-market." },
    brand: { logoText: "DB", accentColor: "#39d2c0" },
    serviceLabel: "Enterprise HRMS — core HR, payroll, performance, talent", recordLabel: "employees", simulatedRecordCount: 4_801,
    discoveryWarnings: ["Performance & 360 review data is sensitive — confirm access controls before bulk export."],
    purposeTemplate: "Enterprise HR — {category} data captured for employment lifecycle and talent management.",
    simulatedDsr: { exportCount: 11, eraseCount: 11 },
  },
  BAMBOOHR: {
    id: "BAMBOOHR", name: "BambooHR", vendor: "BambooHR LLC",
    category: "HR", authType: "API_KEY", apiBaseUrl: "",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "US-based; statutory retention is per-jurisdiction. Indian users need cross-border disclosure.", dataResidency: "US (default).", indianFootprint: "Common in Indian SaaS B2B with US/EU clients." },
    brand: { logoText: "BB", accentColor: "#73c41d" },
    serviceLabel: "HRMS — onboarding, time-off, performance", recordLabel: "employees", simulatedRecordCount: 612,
    discoveryWarnings: ["Cross-border transfer disclosure required (US-based)."],
    purposeTemplate: "HR — {category} data captured for employment lifecycle.",
    simulatedDsr: { exportCount: 8, eraseCount: 8 },
  },
  DROPBOX: {
    id: "DROPBOX", name: "Dropbox", vendor: "Dropbox, Inc.",
    category: "STORAGE_DOC", authType: "OAUTH2", apiBaseUrl: "https://api.dropboxapi.com",
    oauthAuthorizeUrl: "https://www.dropbox.com/oauth2/authorize", oauthTokenUrl: "https://api.dropboxapi.com/oauth2/token",
    oauthScopes: ["files.metadata.read", "files.content.read"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "Dropbox 30-day deleted-files window. Permanent purge requires explicit call.", dataResidency: "US/EU/AU/JP. No India DC.", indianFootprint: "Common in Indian SMB file sharing." },
    brand: { logoText: "DX", accentColor: "#0061ff" },
    serviceLabel: "File storage + sync + sharing", recordLabel: "files + folders", simulatedRecordCount: 12_432,
    discoveryWarnings: ["Cross-border transfer disclosure required.", "Public-link sharing is a §16 surface — audit them."],
    purposeTemplate: "File storage — {category} data captured as uploaded documents and shared folders.",
    simulatedDsr: { exportCount: 10, eraseCount: 10 },
  },
  ONEDRIVE: {
    id: "ONEDRIVE", name: "Microsoft OneDrive", vendor: "Microsoft Corporation",
    category: "STORAGE_DOC", authType: "OAUTH2", apiBaseUrl: "https://graph.microsoft.com",
    oauthAuthorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize", oauthTokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    oauthScopes: ["Files.Read.All"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "OneDrive deleted-items 30-day default. Tenant retention policies override.", dataResidency: "India regions available (Microsoft Multi-Geo).", indianFootprint: "Default storage for Indian Microsoft 365 customers." },
    brand: { logoText: "OD", accentColor: "#0078d4" },
    serviceLabel: "File storage + sync — Office docs, uploads", recordLabel: "files + folders", simulatedRecordCount: 18_842,
    discoveryWarnings: ["Confirm tenant residency setting matches the privacy notice claim."],
    purposeTemplate: "File storage — {category} data captured for Office docs, uploads, and shared workspaces.",
    simulatedDsr: { exportCount: 13, eraseCount: 13 },
  },
  MYSQL: {
    id: "MYSQL", name: "MySQL", vendor: "Self-hosted / RDS / Aurora / PlanetScale",
    category: "DATABASE", authType: "CONNECTION_STRING", apiBaseUrl: "",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: false, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "FK constraints + replication state can block DELETE.", dataResidency: "Depends on host.", indianFootprint: "Most common LAMP-era DB; long tail in Indian PHP shops." },
    brand: { logoText: "MY", accentColor: "#00758f" },
    serviceLabel: "Application database — typically users, orders, sessions", recordLabel: "rows across PII tables", simulatedRecordCount: 142_801,
    discoveryWarnings: [
      "Foreign-key constraints can block DELETE; CASCADE plan generated.",
      "Binary log retention may resurrect deleted rows on replicas — confirm purge.",
    ],
    purposeTemplate: "Application database — {category} data captured to operate the product.",
    simulatedDsr: { exportCount: 32, eraseCount: 32 },
  },
  SNOWFLAKE: {
    id: "SNOWFLAKE", name: "Snowflake", vendor: "Snowflake Inc.",
    category: "DATA_WAREHOUSE", authType: "API_KEY", apiBaseUrl: "",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: false, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "Time-Travel + Fail-safe means deleted data can be queried historically; require explicit data clearance.", dataResidency: "Region-bound; AP-South-1 (Mumbai) for India residency.", indianFootprint: "Mid-market + enterprise Indian analytics." },
    brand: { logoText: "SN", accentColor: "#29b5e8" },
    serviceLabel: "Cloud data warehouse — analytics on enriched PII", recordLabel: "rows across PII tables", simulatedRecordCount: 1_240_804,
    discoveryWarnings: [
      "Time-Travel retains deleted rows (default 1 day, up to 90 days). Set to 0 for sensitive tables.",
      "Confirm Mumbai region pinning for India residency.",
    ],
    purposeTemplate: "Data warehouse — {category} data captured for analytics, reporting, and BI.",
    simulatedDsr: { exportCount: 96, eraseCount: 96 },
  },
  BIGQUERY: {
    id: "BIGQUERY", name: "Google BigQuery", vendor: "Google LLC",
    category: "DATA_WAREHOUSE", authType: "API_KEY", apiBaseUrl: "https://bigquery.googleapis.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: false, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "Time travel default 7 days. Streaming buffer holds rows ~90 minutes — DELETE statement covers both.", dataResidency: "asia-south1 (Mumbai) / asia-south2 (Delhi). Confirm dataset region.", indianFootprint: "Default DW for Indian GA4 / Firebase customers." },
    brand: { logoText: "BQ", accentColor: "#669df6" },
    serviceLabel: "Serverless data warehouse — analytics + ML", recordLabel: "rows across PII tables", simulatedRecordCount: 2_481_902,
    discoveryWarnings: [
      "Confirm asia-south1 (Mumbai) region for India residency.",
      "Time travel retains deleted rows up to 7 days by default.",
    ],
    purposeTemplate: "Serverless data warehouse — {category} data captured for analytics and ML.",
    simulatedDsr: { exportCount: 124, eraseCount: 124 },
  },
  AMAZON_SELLER: {
    id: "AMAZON_SELLER", name: "Amazon Seller Central", vendor: "Amazon.com, Inc.",
    category: "MARKETPLACE", authType: "OAUTH2", apiBaseUrl: "https://sellingpartnerapi-eu.amazon.com",
    oauthAuthorizeUrl: "https://sellercentral.amazon.in/apps/authorize/consent", oauthTokenUrl: "https://api.amazon.com/auth/o2/token",
    oauthScopes: ["sellingpartnerapi::orders", "sellingpartnerapi::reports"],
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "Buyer PII is access-restricted to fulfilment use-case only; Amazon enforces data-handling rules.", dataResidency: "Amazon India (in.amazon.com) for Indian sellers.", indianFootprint: "Largest Indian marketplace — most Indian D2C also sells here." },
    brand: { logoText: "AZ", accentColor: "#ff9900" },
    serviceLabel: "Marketplace seller — orders, returns, buyer messages", recordLabel: "orders + buyer-restricted PII", simulatedRecordCount: 27_402,
    discoveryWarnings: [
      "Amazon Data Protection Policy: buyer PII may only be retained for ≤30 days and only for fulfilment.",
      "Storing buyer PII outside the explicit 30-day fulfilment window is a violation.",
    ],
    purposeTemplate: "Marketplace operations — {category} data captured for order fulfilment (Amazon DPP-bound).",
    simulatedDsr: { exportCount: 18, eraseCount: 18 },
  },
  FLIPKART_SELLER: {
    id: "FLIPKART_SELLER", name: "Flipkart Seller Hub", vendor: "Flipkart Internet Pvt Ltd",
    category: "MARKETPLACE", authType: "API_KEY", apiBaseUrl: "https://api.flipkart.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "Flipkart seller terms: buyer PII for fulfilment only.", dataResidency: "India only.", indianFootprint: "Indian marketplace #2; major D2C channel." },
    brand: { logoText: "FK", accentColor: "#2874f0" },
    serviceLabel: "Marketplace seller — orders, listings, buyer details", recordLabel: "orders + buyer-restricted PII", simulatedRecordCount: 18_201,
    discoveryWarnings: ["Flipkart seller policy bounds buyer PII to fulfilment-only retention."],
    purposeTemplate: "Marketplace operations — {category} data captured for order fulfilment.",
    simulatedDsr: { exportCount: 14, eraseCount: 14 },
  },
  UNICOMMERCE: {
    id: "UNICOMMERCE", name: "Unicommerce", vendor: "Unicommerce eSolutions Pvt Ltd",
    category: "ECOMMERCE", authType: "API_KEY", apiBaseUrl: "https://api.unicommerce.com",
    capabilities: { discovery: true, dsrAccess: true, dsrErasure: true, dsrCorrection: true, grievanceIngest: false, webhooks: true, purgeProof: true },
    dpdpNotes: { legalBasisFloor: "Multi-channel order data with marketplace constraints (Amazon DPP, Flipkart) — retention bounded.", dataResidency: "India only.", indianFootprint: "Gurugram-origin. India's #1 D2C order management." },
    brand: { logoText: "UC", accentColor: "#e6231c" },
    serviceLabel: "Multi-channel order management + warehouse + returns", recordLabel: "orders + SKUs + buyers", simulatedRecordCount: 43_812,
    discoveryWarnings: [
      "Marketplace-channel buyer PII inherits Amazon DPP / Flipkart retention bounds.",
      "Cross-channel identity merges may resurrect deleted records — audit consolidation runs.",
    ],
    purposeTemplate: "Order management — {category} data captured for multi-channel fulfilment, warehouse, and returns.",
    simulatedDsr: { exportCount: 23, eraseCount: 23 },
  },
};

export const CONNECTORS_PHASE_3 = PHASE_3A as Record<Phase3Type, ConnectorDefinition>;

/* ------------------------------------------------------------------ */
/*  PHASE_3_DISCOVERY_SCHEMAS — sample PII fields per connector        */
/* ------------------------------------------------------------------ */

const CONTACT_F = (sys: string, name: string, conf = 0.95): ConnectorDiscoveredField => ({
  systemName: sys, fieldName: name, category: "Contact", identifierType: "Direct identifier", confidence: conf, legalBasisHint: "Legitimate use", retentionHint: "Per app retention policy",
});
const IDENT_F = (sys: string, name: string, conf = 0.94): ConnectorDiscoveredField => ({
  systemName: sys, fieldName: name, category: "Identity", identifierType: "Direct identifier", confidence: conf, legalBasisHint: "Legitimate use", retentionHint: "Per app retention policy",
});
const PREF_F = (sys: string, name: string, conf = 0.78): ConnectorDiscoveredField => ({
  systemName: sys, fieldName: name, category: "Preference", identifierType: "Operational attribute", confidence: conf, legalBasisHint: "Consent", retentionHint: "Until withdrawal",
});
const FIN_F = (sys: string, name: string, conf = 0.92): ConnectorDiscoveredField => ({
  systemName: sys, fieldName: name, category: "Financial", identifierType: "Operational attribute", confidence: conf, legalBasisHint: "Legitimate use (financial)", retentionHint: "RBI: 5 years from txn",
});
const DEV_F = (sys: string, name: string, conf = 0.74): ConnectorDiscoveredField => ({
  systemName: sys, fieldName: name, category: "Device", identifierType: "Persistent identifier", confidence: conf, legalBasisHint: "Security", retentionHint: "Until logout",
});
const LOC_F = (sys: string, name: string, conf = 0.86): ConnectorDiscoveredField => ({
  systemName: sys, fieldName: name, category: "Location", identifierType: "Direct identifier", confidence: conf, legalBasisHint: "Legitimate use", retentionHint: "Per app retention policy",
});
const SENS_F = (sys: string, name: string, conf = 0.7): ConnectorDiscoveredField => ({
  systemName: sys, fieldName: name, category: "Identity", identifierType: "Sensitive identifier", confidence: conf, legalBasisHint: "Legal obligation", retentionHint: "Per regulatory schedule",
});
const BEH_F = (sys: string, name: string, conf = 0.74): ConnectorDiscoveredField => ({
  systemName: sys, fieldName: name, category: "Behavior", identifierType: "Operational attribute", confidence: conf, legalBasisHint: "Legitimate use", retentionHint: "12 months",
});
const SUP_F = (sys: string, name: string, conf = 0.78): ConnectorDiscoveredField => ({
  systemName: sys, fieldName: name, category: "Support", identifierType: "Free-text PII", confidence: conf, legalBasisHint: "Legitimate use", retentionHint: "24 months",
});

export const PHASE_3_DISCOVERY_SCHEMAS: Record<Phase3Type, ConnectorDiscoveredField[]> | any = {
  GOOGLE_WORKSPACE: [IDENT_F("Google Workspace", "users.primaryEmail"), IDENT_F("Google Workspace", "users.fullName"), CONTACT_F("Google Workspace", "users.recoveryPhone"), DEV_F("Google Workspace", "tokens.userAgent"), LOC_F("Google Workspace", "loginActivity.ipAddress"), SUP_F("Google Workspace", "drive.sharedFiles[].owner"), SENS_F("Google Workspace", "drive.files{personal-aadhaar.xlsx}")],
  MOENGAGE: [CONTACT_F("MoEngage", "user.email"), IDENT_F("MoEngage", "user.first_name"), CONTACT_F("MoEngage", "user.mobile"), DEV_F("MoEngage", "user.deviceId"), PREF_F("MoEngage", "user.attributes.consent"), BEH_F("MoEngage", "events.click_email"), LOC_F("MoEngage", "user.geo.country", 0.7)],
  WEBENGAGE: [CONTACT_F("WebEngage", "user.email"), IDENT_F("WebEngage", "user.firstName"), CONTACT_F("WebEngage", "user.phone"), DEV_F("WebEngage", "user.deviceToken"), PREF_F("WebEngage", "user.optIn.email"), BEH_F("WebEngage", "events.purchase"), LOC_F("WebEngage", "user.country", 0.7)],
  CLEVERTAP: [CONTACT_F("CleverTap", "profile.Email"), IDENT_F("CleverTap", "profile.Name"), CONTACT_F("CleverTap", "profile.Phone"), DEV_F("CleverTap", "profile.devices[].deviceId"), PREF_F("CleverTap", "profile.MSG-email"), BEH_F("CleverTap", "events.Charged"), LOC_F("CleverTap", "profile.Country", 0.7)],
  GUPSHUP: [CONTACT_F("Gupshup", "contact.phone"), IDENT_F("Gupshup", "contact.name", 0.85), SUP_F("Gupshup", "messages.body", 0.74), DEV_F("Gupshup", "session.deviceId", 0.66), PREF_F("Gupshup", "contact.optIn"), BEH_F("Gupshup", "events.delivery_status"), LOC_F("Gupshup", "contact.country", 0.6)],
  EXOTEL: [CONTACT_F("Exotel", "call.from"), CONTACT_F("Exotel", "call.to"), SUP_F("Exotel", "call.recording_url", 0.62), DEV_F("Exotel", "call.userAgent"), BEH_F("Exotel", "call.duration_sec"), SENS_F("Exotel", "call.transcript", 0.55), LOC_F("Exotel", "call.location_circle", 0.7)],
  WHATSAPP_BUSINESS: [CONTACT_F("WhatsApp Business", "contact.wa_id"), IDENT_F("WhatsApp Business", "contact.profile.name", 0.85), SUP_F("WhatsApp Business", "messages.text.body", 0.7), PREF_F("WhatsApp Business", "contact.optIn"), BEH_F("WhatsApp Business", "messages.status"), DEV_F("WhatsApp Business", "session.phoneNumberId"), SENS_F("WhatsApp Business", "media.attachments", 0.55)],
  CASHFREE: [CONTACT_F("Cashfree", "customer.email", 0.97), CONTACT_F("Cashfree", "customer.phone", 0.96), IDENT_F("Cashfree", "customer.name", 0.95), FIN_F("Cashfree", "payment.amount", 0.99), FIN_F("Cashfree", "payment.method", 0.95), SENS_F("Cashfree", "settlement.utr", 0.75), FIN_F("Cashfree", "refund.id", 0.9)],
  PAYU: [CONTACT_F("PayU", "customer.email", 0.97), CONTACT_F("PayU", "customer.phone", 0.96), IDENT_F("PayU", "customer.firstname", 0.94), FIN_F("PayU", "txn.amount", 0.99), FIN_F("PayU", "txn.mode", 0.95), SENS_F("PayU", "card.last4", 0.7), FIN_F("PayU", "settlement.id", 0.9)],
  SHIPROCKET: [IDENT_F("Shiprocket", "shipment.consignee.name", 0.95), CONTACT_F("Shiprocket", "shipment.consignee.phone", 0.94), CONTACT_F("Shiprocket", "shipment.consignee.email"), LOC_F("Shiprocket", "shipment.address_line", 0.93), LOC_F("Shiprocket", "shipment.pincode", 0.95), FIN_F("Shiprocket", "shipment.cod_amount", 0.92), DEV_F("Shiprocket", "events.scan_at_hub", 0.7)],
  MICROSOFT_365: [IDENT_F("Microsoft 365", "users.userPrincipalName"), IDENT_F("Microsoft 365", "users.displayName"), CONTACT_F("Microsoft 365", "users.mobilePhone"), DEV_F("Microsoft 365", "signIns.deviceDetail"), LOC_F("Microsoft 365", "signIns.location.city", 0.8), SUP_F("Microsoft 365", "messages.subject", 0.7), SENS_F("Microsoft 365", "files.personal-payslip.pdf", 0.6)],
  MAILCHIMP: [CONTACT_F("Mailchimp", "members.email_address", 0.98), IDENT_F("Mailchimp", "members.merge_fields.FNAME"), IDENT_F("Mailchimp", "members.merge_fields.LNAME"), PREF_F("Mailchimp", "members.status"), BEH_F("Mailchimp", "members.stats.opens"), DEV_F("Mailchimp", "members.last_changed"), LOC_F("Mailchimp", "members.location.country_code", 0.75)],
  SENDGRID: [CONTACT_F("SendGrid", "contacts.email", 0.97), IDENT_F("SendGrid", "contacts.first_name"), BEH_F("SendGrid", "events.event"), DEV_F("SendGrid", "events.useragent"), LOC_F("SendGrid", "events.ip"), PREF_F("SendGrid", "suppressions.bounce"), SUP_F("SendGrid", "messages.subject", 0.65)],
  TWILIO: [CONTACT_F("Twilio", "messages.to", 0.97), CONTACT_F("Twilio", "messages.from"), SUP_F("Twilio", "messages.body", 0.72), BEH_F("Twilio", "messages.status"), DEV_F("Twilio", "calls.from_carrier"), LOC_F("Twilio", "calls.from_country"), SENS_F("Twilio", "recordings.url", 0.6)],
  STRIPE: [CONTACT_F("Stripe", "customers.email", 0.98), IDENT_F("Stripe", "customers.name"), CONTACT_F("Stripe", "customers.phone"), FIN_F("Stripe", "charges.amount", 0.99), SENS_F("Stripe", "payment_methods.card.last4", 0.7), LOC_F("Stripe", "customers.address.country"), FIN_F("Stripe", "subscriptions.status", 0.9)],
  SALESFORCE: [CONTACT_F("Salesforce", "Contact.Email", 0.97), IDENT_F("Salesforce", "Contact.Name"), CONTACT_F("Salesforce", "Contact.Phone"), IDENT_F("Salesforce", "Account.Name", 0.85), SUP_F("Salesforce", "Case.Description", 0.7), PREF_F("Salesforce", "Contact.HasOptedOutOfEmail"), LOC_F("Salesforce", "Contact.MailingCountry", 0.78)],
  SLACK: [CONTACT_F("Slack", "users.profile.email", 0.96), IDENT_F("Slack", "users.profile.real_name"), DEV_F("Slack", "users.tz"), SUP_F("Slack", "messages.text", 0.7), PREF_F("Slack", "users.is_admin"), BEH_F("Slack", "messages.reactions"), LOC_F("Slack", "users.locale", 0.65)],
  GOOGLE_DRIVE: [IDENT_F("Google Drive", "files.owners[].emailAddress", 0.96), IDENT_F("Google Drive", "files.owners[].displayName"), SUP_F("Google Drive", "files.permissions[].emailAddress", 0.8), SENS_F("Google Drive", "files{aadhaar-scan.pdf}", 0.65), SENS_F("Google Drive", "files{customer-pii.xlsx}", 0.7), DEV_F("Google Drive", "files.modifiedByMeTime", 0.6), BEH_F("Google Drive", "files.viewersCanCopyContent")],
  NOTION: [IDENT_F("Notion", "users.person.email", 0.94), IDENT_F("Notion", "users.name"), SUP_F("Notion", "pages.text.content", 0.7), DEV_F("Notion", "blocks.last_edited_by", 0.65), SENS_F("Notion", "databases{customer-list}", 0.6), PREF_F("Notion", "users.bot.workspace_name", 0.55), BEH_F("Notion", "pages.last_edited_time")],
  ZENDESK: [CONTACT_F("Zendesk", "users.email", 0.97), IDENT_F("Zendesk", "users.name"), CONTACT_F("Zendesk", "users.phone"), SUP_F("Zendesk", "tickets.description", 0.78), SUP_F("Zendesk", "tickets.attachments", 0.66), PREF_F("Zendesk", "users.tags"), LOC_F("Zendesk", "users.locale", 0.7)],
  KLAVIYO: [CONTACT_F("Klaviyo", "profiles.email"), IDENT_F("Klaviyo", "profiles.first_name"), CONTACT_F("Klaviyo", "profiles.phone_number"), PREF_F("Klaviyo", "profiles.subscriptions.email"), BEH_F("Klaviyo", "events.OrderPlaced"), LOC_F("Klaviyo", "profiles.location.country"), DEV_F("Klaviyo", "profiles.last_event_date")],
  AUTH0: [CONTACT_F("Auth0", "user.email"), IDENT_F("Auth0", "user.name"), DEV_F("Auth0", "logins.user_agent"), LOC_F("Auth0", "logins.ip"), PREF_F("Auth0", "user.app_metadata"), BEH_F("Auth0", "logins.event"), SENS_F("Auth0", "user.identities[].provider", 0.6)],
  OKTA: [CONTACT_F("Okta", "users.profile.email"), IDENT_F("Okta", "users.profile.firstName"), CONTACT_F("Okta", "users.profile.mobilePhone"), DEV_F("Okta", "factors.profile.userAgent"), LOC_F("Okta", "syslog.client.ipAddress"), PREF_F("Okta", "users.status"), SENS_F("Okta", "factors.factorType", 0.65)],
  FIREBASE_AUTH: [CONTACT_F("Firebase Auth", "user.email"), IDENT_F("Firebase Auth", "user.displayName"), CONTACT_F("Firebase Auth", "user.phoneNumber"), DEV_F("Firebase Auth", "user.metadata.lastSignInTime"), LOC_F("Firebase Auth", "user.metadata.lastSignInIp", 0.7), PREF_F("Firebase Auth", "user.providerData[].providerId"), SENS_F("Firebase Auth", "user.uid", 0.85)],
  GOOGLE_ANALYTICS_4: [DEV_F("GA4", "user_pseudo_id", 0.95), IDENT_F("GA4", "user_id", 0.85), DEV_F("GA4", "device.web_info.browser"), LOC_F("GA4", "geo.country", 0.85), BEH_F("GA4", "events.page_view"), PREF_F("GA4", "user_properties.consent_state"), DEV_F("GA4", "device.advertising_id", 0.7)],
  MIXPANEL: [DEV_F("Mixpanel", "$distinct_id", 0.95), CONTACT_F("Mixpanel", "$properties.$email", 0.85), IDENT_F("Mixpanel", "$properties.$first_name"), DEV_F("Mixpanel", "$properties.$browser"), LOC_F("Mixpanel", "$properties.$country_code", 0.7), BEH_F("Mixpanel", "events.$track"), PREF_F("Mixpanel", "$properties.subscribed", 0.65)],
  AMPLITUDE: [DEV_F("Amplitude", "amplitude_id", 0.95), IDENT_F("Amplitude", "user_id", 0.85), DEV_F("Amplitude", "device_brand"), LOC_F("Amplitude", "country", 0.7), BEH_F("Amplitude", "events.event_type"), PREF_F("Amplitude", "user_properties.subscribed"), DEV_F("Amplitude", "ip_address", 0.7)],
  SEGMENT: [IDENT_F("Segment", "userId", 0.9), DEV_F("Segment", "anonymousId", 0.95), CONTACT_F("Segment", "traits.email"), IDENT_F("Segment", "traits.name"), BEH_F("Segment", "events.track"), PREF_F("Segment", "traits.unsubscribed"), LOC_F("Segment", "context.location.country", 0.65)],
  POSTHOG: [DEV_F("PostHog", "person.distinct_id", 0.95), CONTACT_F("PostHog", "person.email"), IDENT_F("PostHog", "person.name"), BEH_F("PostHog", "events.event"), DEV_F("PostHog", "session_recordings.id", 0.85), LOC_F("PostHog", "person.geoip.country_code", 0.7), PREF_F("PostHog", "person.feature_flags", 0.65)],
  PIPEDRIVE: [CONTACT_F("Pipedrive", "persons.email", 0.97), IDENT_F("Pipedrive", "persons.name"), CONTACT_F("Pipedrive", "persons.phone"), IDENT_F("Pipedrive", "deals.title", 0.7), SUP_F("Pipedrive", "activities.note", 0.65), PREF_F("Pipedrive", "persons.marketing_status"), LOC_F("Pipedrive", "persons.country_code", 0.7)],
  LEADSQUARED: [CONTACT_F("LeadSquared", "Lead.EmailAddress"), IDENT_F("LeadSquared", "Lead.FirstName"), CONTACT_F("LeadSquared", "Lead.Phone"), SUP_F("LeadSquared", "Lead.Notes", 0.65), PREF_F("LeadSquared", "Lead.OptInDetails"), BEH_F("LeadSquared", "Activity.Type"), SENS_F("LeadSquared", "Lead.PAN", 0.6)],
  WOOCOMMERCE: [CONTACT_F("WooCommerce", "customer.email"), IDENT_F("WooCommerce", "customer.first_name"), IDENT_F("WooCommerce", "customer.last_name"), CONTACT_F("WooCommerce", "customer.billing.phone"), LOC_F("WooCommerce", "customer.shipping.country"), FIN_F("WooCommerce", "order.total", 0.95), PREF_F("WooCommerce", "customer.subscribed_to_newsletters")],
  MAGENTO: [CONTACT_F("Magento", "customer.email", 0.97), IDENT_F("Magento", "customer.firstname"), IDENT_F("Magento", "customer.lastname"), CONTACT_F("Magento", "customer.addresses[].telephone"), LOC_F("Magento", "customer.addresses[].country_id"), FIN_F("Magento", "order.grand_total", 0.95), PREF_F("Magento", "customer.is_subscribed")],
  INTERCOM: [CONTACT_F("Intercom", "users.email", 0.97), IDENT_F("Intercom", "users.name"), CONTACT_F("Intercom", "users.phone"), SUP_F("Intercom", "conversations.body", 0.74), DEV_F("Intercom", "users.last_seen_user_agent"), LOC_F("Intercom", "users.location.country"), PREF_F("Intercom", "users.unsubscribed_from_emails")],
  JIRA: [CONTACT_F("Jira", "user.emailAddress"), IDENT_F("Jira", "user.displayName"), SUP_F("Jira", "issue.description", 0.78), SUP_F("Jira", "issue.comments[].body", 0.7), DEV_F("Jira", "issue.reporter.userAgent", 0.55), PREF_F("Jira", "issue.labels"), SENS_F("Jira", "issue.attachments", 0.55)],
  PAYTM_BUSINESS: [CONTACT_F("Paytm", "merchant.contact.email", 0.97), CONTACT_F("Paytm", "customer.mobile", 0.96), IDENT_F("Paytm", "customer.name", 0.94), FIN_F("Paytm", "txn.amount", 0.99), FIN_F("Paytm", "txn.method", 0.95), SENS_F("Paytm", "settlement.utr", 0.7), FIN_F("Paytm", "refund.id", 0.9)],
  PHONEPE_BUSINESS: [CONTACT_F("PhonePe", "merchant.email"), CONTACT_F("PhonePe", "customer.mobile", 0.96), IDENT_F("PhonePe", "customer.upiHandle", 0.85), FIN_F("PhonePe", "txn.amount", 0.99), FIN_F("PhonePe", "txn.method", 0.95), SENS_F("PhonePe", "settlement.utr", 0.7), FIN_F("PhonePe", "refund.id", 0.9)],
  DELHIVERY: [IDENT_F("Delhivery", "shipment.consignee.name"), CONTACT_F("Delhivery", "shipment.consignee.phone"), CONTACT_F("Delhivery", "shipment.consignee.email"), LOC_F("Delhivery", "shipment.address1", 0.93), LOC_F("Delhivery", "shipment.pincode", 0.95), FIN_F("Delhivery", "shipment.cod_amount", 0.92), DEV_F("Delhivery", "tracking.scan_location", 0.7)],
  BLUEDART: [IDENT_F("BlueDart", "consignee.name"), CONTACT_F("BlueDart", "consignee.phone"), LOC_F("BlueDart", "consignee.address", 0.92), LOC_F("BlueDart", "consignee.pincode", 0.95), FIN_F("BlueDart", "shipment.declared_value", 0.9), SENS_F("BlueDart", "consignee.idProof", 0.6), DEV_F("BlueDart", "tracking.scan_at", 0.7)],
  KEKA: [CONTACT_F("Keka", "employee.workEmail"), IDENT_F("Keka", "employee.firstName"), CONTACT_F("Keka", "employee.personalPhone"), SENS_F("Keka", "employee.aadhaarLast4", 0.7), SENS_F("Keka", "employee.panNumber", 0.7), FIN_F("Keka", "payroll.netPay", 0.9), LOC_F("Keka", "employee.address", 0.85)],
  DARWINBOX: [CONTACT_F("Darwinbox", "employee.email"), IDENT_F("Darwinbox", "employee.fullName"), CONTACT_F("Darwinbox", "employee.phone"), SENS_F("Darwinbox", "employee.aadhaar", 0.7), FIN_F("Darwinbox", "payroll.gross", 0.9), SUP_F("Darwinbox", "performance.review_text", 0.7), LOC_F("Darwinbox", "employee.permanentAddress", 0.85)],
  BAMBOOHR: [CONTACT_F("BambooHR", "employees.workEmail"), IDENT_F("BambooHR", "employees.firstName"), CONTACT_F("BambooHR", "employees.mobilePhone"), FIN_F("BambooHR", "payroll.payRate", 0.85), LOC_F("BambooHR", "employees.address1", 0.85), SUP_F("BambooHR", "performance.review", 0.7), SENS_F("BambooHR", "employees.ssn", 0.55)],
  DROPBOX: [IDENT_F("Dropbox", "files.owner.email", 0.95), IDENT_F("Dropbox", "files.owner.display_name"), SUP_F("Dropbox", "files.shared_folders[].permissions", 0.75), SENS_F("Dropbox", "files{kyc-scans/*}", 0.6), DEV_F("Dropbox", "files.last_edited_by", 0.65), BEH_F("Dropbox", "files.access_count"), LOC_F("Dropbox", "team_log.country", 0.6)],
  ONEDRIVE: [IDENT_F("OneDrive", "drive.owner.user.email", 0.94), IDENT_F("OneDrive", "drive.owner.user.displayName"), SUP_F("OneDrive", "items.permissions[].grantedTo.user.email", 0.78), SENS_F("OneDrive", "items{personal-payslip.pdf}", 0.6), DEV_F("OneDrive", "items.lastModifiedBy", 0.65), BEH_F("OneDrive", "activities.access"), LOC_F("OneDrive", "auditLog.location", 0.6)],
  MYSQL: [CONTACT_F("MySQL", "users.email", 0.96), IDENT_F("MySQL", "users.full_name"), CONTACT_F("MySQL", "users.phone"), SENS_F("MySQL", "users.password_hash", 0.99), LOC_F("MySQL", "orders.shipping_address", 0.91), DEV_F("MySQL", "events.user_agent", 0.71), DEV_F("MySQL", "audit_log.ip_address", 0.83)],
  SNOWFLAKE: [CONTACT_F("Snowflake", "USERS.EMAIL"), IDENT_F("Snowflake", "USERS.FULL_NAME"), DEV_F("Snowflake", "EVENTS.SESSION_ID", 0.85), LOC_F("Snowflake", "EVENTS.GEO_COUNTRY"), FIN_F("Snowflake", "ORDERS.AMOUNT", 0.95), BEH_F("Snowflake", "EVENTS.PAGE_PATH"), SENS_F("Snowflake", "USERS.AADHAAR_HASH", 0.7)],
  BIGQUERY: [DEV_F("BigQuery", "events.user_pseudo_id", 0.95), IDENT_F("BigQuery", "users.user_id"), CONTACT_F("BigQuery", "users.email"), LOC_F("BigQuery", "geo.country"), FIN_F("BigQuery", "orders.value", 0.95), BEH_F("BigQuery", "events.event_name"), DEV_F("BigQuery", "device.advertising_id", 0.7)],
  AMAZON_SELLER: [IDENT_F("Amazon Seller", "order.BuyerName"), CONTACT_F("Amazon Seller", "order.BuyerEmail"), CONTACT_F("Amazon Seller", "order.ShippingAddress.Phone"), LOC_F("Amazon Seller", "order.ShippingAddress.PostalCode", 0.95), FIN_F("Amazon Seller", "order.OrderTotal.Amount", 0.95), BEH_F("Amazon Seller", "order.NumberOfItemsShipped"), PREF_F("Amazon Seller", "order.IsBusinessOrder")],
  FLIPKART_SELLER: [IDENT_F("Flipkart Seller", "order.buyer.name"), CONTACT_F("Flipkart Seller", "order.buyer.phone"), CONTACT_F("Flipkart Seller", "order.buyer.email"), LOC_F("Flipkart Seller", "order.shipping.address", 0.93), LOC_F("Flipkart Seller", "order.shipping.pincode", 0.95), FIN_F("Flipkart Seller", "order.totalAmount", 0.95), PREF_F("Flipkart Seller", "order.payment_method")],
  UNICOMMERCE: [IDENT_F("Unicommerce", "order.customer.name"), CONTACT_F("Unicommerce", "order.customer.phone"), CONTACT_F("Unicommerce", "order.customer.email"), LOC_F("Unicommerce", "order.shipping.address", 0.93), FIN_F("Unicommerce", "order.totalAmount", 0.95), DEV_F("Unicommerce", "order.salesChannel"), PREF_F("Unicommerce", "order.payment_method")],
};
